# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/874a67ea-8fb1-4e61-9a47-5f4413436393";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

##### Graphics code for flickering issue on videos

# For possible better graphics driver. Working with: Intel 6th Gen i7-6700T with quicksync
  # Enable OpenGL and hardware acceleration
  hardware.graphics = {
    enable = true;
    enable32Bit = true; # For compatibility with 32-bit apps
    extraPackages = with pkgs; [
      intel-media-driver # For Skylake (libva-intel-driver for older GPUs)
      vaapiIntel # VAAPI for Intel GPU
      vaapiVdpau # Fallback for some apps
      libvdpau-va-gl # VDPAU to VAAPI bridge
    ];
  };

  # Ensure Intel GPU drivers are loaded
  services.xserver.videoDrivers = [ "intel" ];

  # Optional: Explicitly enable VAAPI in environment
  environment.variables = {
    LIBVA_DRIVER_NAME = "iHD"; # Use intel-media-driver for Skylake
  };

  environment.systemPackages = with pkgs; [
    libva-utils # For vainfo to verify VAAPI
    intel-gpu-tools # For monitoring GPU usage
    alsa-utils # For speaker-test
  ];

  # For fixing graphics blackouts on streams
  boot.kernelParams = [
    "i915.enable_psr=0" # Disable panel self-refresh (fixes blackouts)
    "i915.fastboot=1"   # Faster modesetting, reduces glitches
    "i915.enable_guc=2"  # Enable GuC firmware for better performance
  ];

  # Bootloader.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";
  boot.loader.grub.useOSProber = true;
  
  #Fix for popping speaker noise
  boot.extraModprobeConfig = ''
    options snd_hda_intel power_save=0 power_save_controller=N
  '';
}
